### ISSUE TITLE
simple_witch_bonus error

### ISSUE THREAD

**Issue by Owned67** [Tabbernaut/L4D2-Plugins#3]
Hello,

l4d2_penalty_bonus.inc in G:\L4D2\\addons\sourcemod\scripting\include\

line 29 for l4d2_penalty_bonus.inc:
 // Adds points to the bonus for the current round
native PBONUS_AddRoundBonus(bonus);

simple_witch_bonus.sp in G:\L4D2\\addons\sourcemod\scripting\
l4d2_penalty_bonus.sp in G:\L4D2\\addons\sourcemod\scripting\

compilation (no error):
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// l4d2_penalty_bonus.sp
// Header size:           4068 bytes
// Code size:             9068 bytes
// Data size:             2576 bytes
// Stack/heap size:      16384 bytes; Total requirements:   32096 bytes
//
// Compilation Time: 0,66 sec
// ----------------------------------------

//// simple_witch_bonus.sp
// Header size:           2920 bytes
// Code size:             4276 bytes
// Data size:             1628 bytes
// Stack/heap size:      16384 bytes; Total requirements:   25208 bytes
//
// Compilation Time: 0,31 sec
// ----------------------------------------

Press enter to exit ...

Start server and error:
[SM] Plugin optional/simple_witch_bonus.smx failed to load: Native "PBONUS_AddRoundBonus" was not found.

**Comment by Tabbernaut** [comment]
If that was a question, the answer is probably just as it 
indicates:

PBONUS_... not found

which means that you have not loaded the Penalty Bonus plugin.
Be advised that loading order makes a difference too, as I 
recall.
So first load the stuff that other plugins depend on.
