### ISSUE TITLE
l4d2_playstats doesn't show any stats on mission lost in coop mode

### ISSUE THREAD

**Issue by vikingo12** [Tabbernaut/L4D2-Plugins#4]

**Comment by czim** [comment]
That's correct. It treats the whole round (including all failures) as a single unit, and only shows the full stats for it when you succeed (eventually).

The whole thing was designed more for versus use, so this may or may not be fine for your coop enjoyment. What would you suggest?

**Comment by vikingo12** [comment]
I was using survivor_mvp from Sir Competitive Rework and it was showing stats on mission lost but not on finale end
Sir's l4d2_playstats doesn't work for me at all,but if the stats on mission lost can't be done it's still okay

**Comment by czim** [comment]
It definitely *can* be done; I don't have much time for it generally, but I'll try and see how I can set it up. I agree that it's better anyway.

**Comment by vikingo12** [comment]
I would definently appreciate your hard work!

**Comment by czim** [comment]
I made a small change that should make this work and print the stats on failing a coop mission. Give it a shot and let me know if it works well enough for you. Version of playstats should be 1.0

**Comment by vikingo12** [comment]
everything works great!!many thanks
